version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Running build script (if present)"
      - npm run build --if-present || echo "No build script found"
      - echo "Running tests (if present)"
      - npm test || echo "No tests defined"

artifacts:
  files:
    - '**/*'
