version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Skipping tests (no test script)"
      # - npm test (lo puedes agregar después)
      - echo "Build phase done"

artifacts:
  files:
    - '**/*'
